### ISSUE TITLE
Terraform scripts to deploy circles-api docker container to ECS

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/infrastructure-provisioning#14]

**Comment by edzillion** [comment]
Using this tute as a starting point: https://thecode.pub/easy-deploy-your-docker-applications-to-aws-using-ecs-and-fargate-a988a1cc842f

**Comment by edzillion** [comment]
@xwvvvvwx told me today that perhaps we can pull the docker image from dockerhub and not use ECR. Just doing some research on that now. 

> In order to pull the image, your ENI must have access to the registry. For Docker Hub and for Amazon ECR, this means your ENI must have access to reach the Internet. You can achieve access to the Internet in a few different ways, but the most common are an Internet Gateway and public IP address or using NAT and a private IP address. For NAT, you can use NAT instances or a NAT gateway.

> If you want to disable Internet access entirely, you'll need to use a registry located inside your VPC instead of a registry that requires Internet access.

https://github.com/aws/amazon-ecs-agent/issues/1128#issuecomment-354884572

**Comment by edzillion** [comment]
I found a good reference repo here: 

https://github.com/nathanpeck/socket.io-chat-fargate

And it seems like you need to add to ECS from docker hub for fargate to work anyway: https://github.com/nathanpeck/socket.io-chat-fargate/blob/3d7727d1616fc6ec6cabf9f0db4d6d290639c149/pipeline.yml#L161

**Comment by xwvvvvwx** [comment]
> And it seems like you need to add to ECS from docker hub for fargate to work anyway: 

What do you mean?

**Comment by edzillion** [comment]
> What do you mean?

The code I quoted seems to show (after `codepipeline` pulling the repo from github) the image being pushed to ECR

```
phases:
            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email)
                - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
                - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
            build:
              commands:
                - docker build --tag "${IMAGE_URI}" ./services/client
            post_build:
              commands:
                - docker push "$IMAGE_URI"
                - printf '{"ImageUri":"%s"}' "$IMAGE_URI" > build.json
```
